name: Build ImmortalWrt Firmware
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x.git
  REPO_BRANCH: openwrt-21.02
  CONFIG_FILE: .config
  SELF_BEFORE_SH: before-update-custom.sh
  SELF_AFTER_SH: after-update-custom.sh
  TZ: Asia/Shanghai
  FEEDS_CONF: feeds.conf.default

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write

    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main

    - name: Checkout
      uses: actions/checkout@main

    - name: Init environment
      run: |
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /srcdir
        sudo chown $USER:$GROUPS /srcdir

    - name: Clone source code
      working-directory: /srcdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /srcdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        [ -f "$FEEDS_CONF" ] && mv "$FEEDS_CONF" openwrt/feeds.conf.default
        [ -f "$SELF_BEFORE_SH" ] && chmod +x "$SELF_BEFORE_SH" && openwrt/../$SELF_BEFORE_SH

    - name: Update & Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom config
      run: |
        [ -e files ] && mv files openwrt/files
        [ -f "$CONFIG_FILE" ] && mv "$CONFIG_FILE" openwrt/.config
        [ -f "$SELF_AFTER_SH" ] && chmod +x "$SELF_AFTER_SH" && openwrt/../$SELF_AFTER_SH

    - name: Download package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -delete

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

        DEVICE=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
        echo "DEVICE_NAME=_$DEVICE" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload bin folder
      uses: actions/upload-artifact@main
      with:
        name: ImmortalWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize firmware
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: Upload firmware only
      uses: actions/upload-artifact@main
      with:
        name: ImmortalWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      run: |
        echo "release_tag=ImmortalWrt_$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        echo "ImmortalWrt build for ${{ env.DEVICE_NAME }}" > release.txt

    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save cache (dl only)
      uses: actions/cache/save@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-openwrt-dl
